/* eslint-disable @typescript-eslint/no-unused-vars */
const medicines = [
    {
      name: "Panadol Extra",
      description: "Pain relief tablet for headaches, toothaches and fever.",
      price: 12.5,
      quantity: 100,
      stockAvailability: true,
      requiredPrescription: false,
      manufacturerDetails: {
        name: "GSK Pharma",
        contact: "+1-800-111-222",
        location: "New York, USA",
      },
      symptoms: "Headache, Fever, Toothache",
      expiryDate: new Date("2026-03-01"),
      image: "/images/panadol.jpg",
    },
    {
      name: "Amoxicillin 500mg",
      description: "Antibiotic used for bacterial infections.",
      price: 25.0,
      quantity: 50,
      stockAvailability: true,
      requiredPrescription: true,
      manufacturerDetails: {
        name: "Pfizer",
        contact: "+44-700-555-111",
        location: "London, UK",
      },
      symptoms: "Infections, Cough, Cold",
      expiryDate: new Date("2025-10-15"),
      image: "/images/amoxicillin.jpg",
    },
    {
      name: "Cetirizine",
      description: "Antihistamine used to relieve allergy symptoms.",
      price: 8.99,
      quantity: 200,
      stockAvailability: true,
      requiredPrescription: false,
      manufacturerDetails: {
        name: "Sun Pharma",
        contact: "+91-22-1234-5678",
        location: "Mumbai, India",
      },
      symptoms: "Allergies, Sneezing, Runny Nose",
      expiryDate: new Date("2027-01-20"),
      image: "/images/cetirizine.jpg",
    },
    {
      name: "Ibuprofen 400mg",
      description: "Nonsteroidal anti-inflammatory drug for pain relief.",
      price: 10.0,
      quantity: 150,
      stockAvailability: true,
      requiredPrescription: false,
      manufacturerDetails: {
        name: "Bayer Healthcare",
        contact: "+49-30-468-111",
        location: "Berlin, Germany",
      },
      symptoms: "Inflammation, Pain, Fever",
      expiryDate: new Date("2026-08-12"),
      image: "/images/ibuprofen.jpg",
    },
    {
      name: "Metformin",
      description: "Oral diabetes medicine that helps control blood sugar.",
      price: 18.75,
      quantity: 120,
      stockAvailability: true,
      requiredPrescription: true,
      manufacturerDetails: {
        name: "Novo Nordisk",
        contact: "+45-888-777",
        location: "Bagsværd, Denmark",
      },
      symptoms: "Type 2 Diabetes",
      expiryDate: new Date("2025-07-01"),
      image: "/images/metformin.jpg",
    },
    {
      name: "Aspirin 81mg",
      description: "Low dose aspirin for heart health.",
      price: 6.5,
      quantity: 300,
      stockAvailability: true,
      requiredPrescription: false,
      manufacturerDetails: {
        name: "Johnson & Johnson",
        contact: "+1-888-555-1212",
        location: "New Jersey, USA",
      },
      symptoms: "Blood thinning, Pain",
      expiryDate: new Date("2026-11-05"),
      image: "/images/aspirin.jpg",
    },
    {
      name: "Cough Syrup",
      description: "Relieves dry and productive coughs.",
      price: 14.0,
      quantity: 80,
      stockAvailability: true,
      requiredPrescription: false,
      manufacturerDetails: {
        name: "Reckitt Benckiser",
        contact: "+44-20-1400-0000",
        location: "Slough, UK",
      },
      symptoms: "Cough, Sore Throat",
      expiryDate: new Date("2025-02-17"),
      image: "/images/cough-syrup.jpg",
    },
    {
      name: "Loratadine",
      description: "Second-generation antihistamine for allergic rhinitis.",
      price: 9.25,
      quantity: 180,
      stockAvailability: true,
      requiredPrescription: false,
      manufacturerDetails: {
        name: "Teva Pharmaceuticals",
        contact: "+972-3-926-7267",
        location: "Petah Tikva, Israel",
      },
      symptoms: "Allergies, Hives",
      expiryDate: new Date("2026-04-10"),
      image: "/images/loratadine.jpg",
    },
    {
      name: "Prednisone",
      description: "Steroid used for inflammation and autoimmune conditions.",
      price: 22.5,
      quantity: 70,
      stockAvailability: true,
      requiredPrescription: true,
      manufacturerDetails: {
        name: "Mylan",
        contact: "+1-304-555-0000",
        location: "Canonsburg, USA",
      },
      symptoms: "Arthritis, Asthma, Allergic Disorders",
      expiryDate: new Date("2025-12-25"),
      image: "/images/prednisone.jpg",
    },
    {
      name: "Vitamin C 1000mg",
      description: "Immune booster and antioxidant supplement.",
      price: 11.99,
      quantity: 250,
      stockAvailability: true,
      requiredPrescription: false,
      manufacturerDetails: {
        name: "Nature Made",
        contact: "+1-877-555-0001",
        location: "California, USA",
      },
      symptoms: "Weak Immunity, Fatigue",
      expiryDate: new Date("2027-06-30"),
      image: "/images/vitamin-c.jpg",
    },
  ];
  