import type { Metadata } from "next";
import { Oxanium, Poppins } from "next/font/google";
import "./globals.css";
import "@ant-design/v5-patch-for-react-19";
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600"] });
const oxanium = Oxanium({
    subsets: ["latin"],
    weight: ["400", "600", "700"],
    variable: "--font-secondary",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${oxanium.variable} ${poppins.className} antialiased`}>
                <div className='min-h-screen'>{children}</div>
            </body>
        </html>
    );
}
