import "@ant-design/v5-patch-for-react-19";
import type { Metadata } from "next";
import { Oxanium, Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/providers";
import { Toaster } from "sonner";


const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600"] });

const oxanium = Oxanium({
    subsets: ["latin"],
    weight: ["400", "600", "700"],
    variable: "--font-secondary",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <Providers>
                <body
                    className={`${oxanium.variable} ${poppins.className} antialiased`}>
                    <Toaster richColors />
                    <div className='min-h-screen'>{children}</div>
                </body>
            </Providers>
        </html>
    );
}
